baseURL: "https://example.com/"
languageCode: en-us
title: The New SSS Blog
theme: github.com/mavidser/hugo-rocinante
paginate: 3
markup:
  highlight:
    style: monokailight
  goldmark:
    renderer:
      unsafe: true
params:
  favicon: /icons/favicon.png
  mainSections:
    - posts
    - photos
  email: steve@ssshupe.com
  smart_email_link:
    - Email
  about: |
    I'm a hobbyist coder and photographer, a close-to-fluent francophile, a semi-retired public agency attorney, a political junkie, a Dad, a husband, a dog-owner, and blogger.
  links:
    - link:
        - name: Email
          href: /contact
          smart_email_link: true
    - link:
        - name: Github
          href: "https://github.com/ssshupe"
          new_tab: true
        - name: Twitter
          href: "https://twitter.com/ssshupe"
          new_tab: true
        - name: Instagram
          href: "https://instagram.com/ssshupe"
          new_tab: true
        - name: Flickr
          href: "https://flickr.com/photos/ssshupe"
          new_tab: true
