baseURL = "http://example.com/"
languageCode = "en-us"
title = "The New SSS Blog"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
buildDrafts = true
sectionPagesMenu = "main"

[params]
    author = "Steve Shupe"
    description = "The new site for my personal blog"
    githubUsername = "SSShupe"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto Slab" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["julia", "go"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/SSShupe/"
    name = "github"
    weight = 6

[[menu.icon]]
    url = "https://twitter.com/ssshupe/"
    name = "twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/ssshupe/"
    name = "linkedin"
    weight = 5

[[menu.icon]]
    url = "https://www.stackoverflow.com/ssshupe/"
    name = "stack-overflow"
    weight = 7

[[menu.icon]]
    url = "https://flickr.com/photos/ssshupe"
    name = "flickr"
    weight = 2

[[menu.icon]]
    url = "https://instagram.com/ssshupe"
    name = "instagram"
    weight = 3